version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # for whatever reason, the YAML value for pnpm is npm
    directory: "/"
    schedule:
      interval: "weekly"
