/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// + Getting started
// + Dashboard
// + Setup and configuration
// + User and team management
// + Authentication and authorization
// + Cluster management
// + Cluster connectivity setup
// + Connector management
// + Metadata management
// + Klaw workflows
// + Notifications
// + FAQs

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    "index",
    {
      type: "category",
      label: "Getting started",
      items: [
        {
          type: "autogenerated",
          dirName: "getting-started", // Generate sidebar slice from docs/getting-started
        },
      ],
    },
    {
      type: "category",
      label: "Dashboard",
      items: [
        {
          type: "autogenerated",
          dirName: "dashboard", // Generate sidebar slice from docs/dashboard
        },
      ],
    },
    {
      type: "category",
      label: "Setup and configuration",
      items: [
        {
          type: "category",
          label: "Klaw installation",
          link: {
            type: "doc",
            id: "setup-configuration/klaw-installation/index",
          },
          items: [
            "setup-configuration/klaw-installation/run-docker",
            "setup-configuration/klaw-installation/run-source",
            "setup-configuration/klaw-installation/configure-klaw-wizard",
          ],
        },
        "setup-configuration/klaw-api-ssl-with-kafka",
        "setup-configuration/high-availability",
        "setup-configuration/settings",
        "setup-configuration/tenant-configuration",
      ],
    },
    {
      type: "category",
      label: "User and team management",
      items: [
        "user-team-management/users-roles-teams",
        "user-team-management/manage-users",
        "user-team-management/manage-roles-permissions",
        {
          type: "category",
          label: "Teams",
          items: [
            "user-team-management/teams/manage-teams",
            "user-team-management/teams/switch-teams",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Authentication and authorization",
      items: [
        {
          type: "category",
          label: "Authentication",
          items: [
            {
              type: "autogenerated",
              dirName: "authentication-authorization/authentication",
            },
          ],
        },
        "authentication-authorization/authorization",
      ],
    },
    {
      type: "category",
      label: "Concepts",
      items: [
        {
          type: "autogenerated",
          dirName: "Concepts", // Generate sidebar slice from docs/concepts
        },
      ],
    },
    {
      type: "category",
      label: "HowTo",
      items: [
        {
          type: "autogenerated",
          dirName: "HowTo", // Generate sidebar slice from docs/howTo
        },
      ],
    },
    "faq",
  ],
  releases: [
    {
      type: "category",
      label: "All releases",
      link: { type: "generated-index", slug: "releases" },
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "releases", // Generate sidebar slices from docs/releases
        },
      ],
    },
  ],
};

module.exports = sidebars;
