/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: "autogenerated", dirName: "." }],
  releases: [
    {
      type: "category",
      label: "All releases",
      link: { type: "generated-index", slug: "releases" },
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "releases", // Generate sidebar slices from docs/releases
        },
      ],
    },
  ],
};

module.exports = sidebars;
