extends: substitution
message: Use '%s' instead of '%s'
level: warning
ignorecase: true
# swap maps tokens in form of bad: good
# Vale will ignore any alerts that match the intended form.
swap:
  "(?<!Klaw )cluster api": Klaw Cluster API
  "(?i)api": API
  "(?i)kafka connect": Kafka Connect
  "(?i)klaw core": Klaw Core
  "(?i)klaw": Klaw