# Detect extraneous apostrophes before 'are'.
# https://vale.sh/explorer/apos_are/
extends: sequence
message: Did you mean "%[1]ss" instead of "%[1]s's"?
tokens:
  - tag: NN
  - pattern: "'s"
  - pattern: "are"
level: error
action:
  name: edit
  params:
    - replace
    - "'"
    - ""