name: "Static code and markdown analysis"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  static_analysis:
    name: Static analysis code and markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set Node and pnpm versions
        id: versions
        shell: bash
        run: |
          NODE_VERSION=$(jq -r '.engines.node' package.json)
          PNPM_VERSION=$(jq -r '.engines.pnpm' package.json)
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "PNPM_VERSION=$PNPM_VERSION" >> $GITHUB_OUTPUT

      - name: Setup node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ steps.versions.outputs.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: ${{ steps.versions.outputs.PNPM_VERSION }}
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Linting code files
        run: pnpm lint:code

      - name: Linting markdown files
        run: pnpm lint:markdown
