name: "Static code and markdown analysis"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  static_analysis:
    name: Static analysis code and markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set Node and pnpm versions
        id: versions
        shell: bash
        run: |
          NODE_VERSION=$(jq -r '.engines.node' package.json)
          PNPM_VERSION=$(jq -r '.engines.pnpm' package.json)
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "PNPM_VERSION=$PNPM_VERSION" >> $GITHUB_OUTPUT

      - name: Setup node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ steps.versions.outputs.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          version: ${{ steps.versions.outputs.PNPM_VERSION }}
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Linting code files
        run: pnpm lint:code

      - name: Linting markdown files
        run: pnpm lint:markdown
