name: "Vale spelling and prose check"
on:
  push:
    branches: ["main"]
    paths:
      - "**.md"
  pull_request:
    branches: ["main"]
    paths:
      - "**.md"

jobs:
  spell-prose-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #v4.1.4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

        # While Vale offers an action, based on review dog, but that didn't work
        # to catch errors that are not in files outside of the diff of the PR
        # We need to run the pipeline for all files at least as long as we introduce
        # new styles frequently. This is why I followed this approach for running Vale.working-directory:
        # https://github.com/reviewdog/reviewdog/issues/1408
      - name: Install Vale
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v2.29.1/vale_2.29.1_Linux_64-bit.tar.gz -O vale.tar.gz
          tar -xvzf vale.tar.gz vale
          rm vale.tar.gz

      - name: Run Vale
        run: ./vale --glob='!.github/vale/styles/*' . --minAlertLevel=error --config=.vale.ini
